use gacha_core::{
    CompiledGame, EngineError, Result, ScopeContext, StateStore, enumerate_transitions,
};
use std::collections::BTreeMap;

#[derive(Debug, Clone)]
pub struct ProbabilityResult {
    pub probability: f64,
    pub surviving_states: usize,
}

/// Computes the probability of obtaining `target_item` within `draws` draws.
///
/// The transition probabilities are generated by the same rule graph used by
/// sampling. Probability mass is accumulated in f64 here to avoid unbounded
/// rational denominator growth in long horizons. One-step engine transitions
/// themselves remain exact rationals.
pub fn probability_of_item_within(
    game: &CompiledGame,
    banner: &str,
    action: &str,
    initial_state: &StateStore,
    context: &ScopeContext,
    target_item: &str,
    draws: u32,
) -> Result<ProbabilityResult> {
    let target = game
        .item_id(target_item)
        .ok_or_else(|| EngineError::new(format!("unknown target item: {target_item}")))?;

    if draws == 0 {
        return Ok(ProbabilityResult {
            probability: 0.0,
            surviving_states: 1,
        });
    }

    let mut active = BTreeMap::<StateStore, f64>::new();
    active.insert(initial_state.clone(), 1.0);
    let mut hit = 0.0_f64;

    for _ in 0..draws {
        let mut next = BTreeMap::<StateStore, f64>::new();
        for (state, mass) in active {
            if mass == 0.0 {
                continue;
            }
            let branches = enumerate_transitions(game, banner, action, &state, context)?;
            for branch in branches {
                let branch_mass = mass * branch.probability.to_f64();
                if branch.outcome.item == target {
                    hit += branch_mass;
                } else {
                    *next.entry(branch.next_state).or_insert(0.0) += branch_mass;
                }
            }
        }
        active = next;
    }

    if !hit.is_finite() {
        return Err(EngineError::new(
            "analysis produced a non-finite probability",
        ));
    }
    Ok(ProbabilityResult {
        probability: hit.clamp(0.0, 1.0),
        surviving_states: active.len(),
    })
}
