[package]
name = "gacha-analysis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
gacha-core = { path = "../gacha-core" }
serde.workspace = true

[dev-dependencies]
gacha-pack = { path = "../gacha-pack" }
serde_json.workspace = true
